// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConcessionariaWeb.Model
{
    public partial class Clientes
    {
        [Required(ErrorMessage = "<b style = 'color : black;' > O Nome do Cliente é obrigatório.</b>", AllowEmptyStrings = false)]
        [Display(Name = "Cliente")]
        [StringLength(100)]
        [Unicode(false)]
        public string cliente { get; set; }

        [Required(ErrorMessage = "<b style = 'color : black;' > O CEP deve conter 8 números.</b>")]
        [StringLength(11, MinimumLength = 11)]
        [Column("CEP")]
        [Unicode(false)]
        public string CEP { get; set; }
        

        [Required(ErrorMessage = "<b style = 'color : black;'>O Endereço do cliente é obrigatório.</b>", AllowEmptyStrings = false)]
        [Display(Name = "Endereço")]
        [StringLength(100)]
        [Unicode(false)]
        public string endereço { get; set; }
        [Key]

        [Column("ID")]
        public int ID { get; set; }
    }
}