// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConcessionariaWeb.Model
{
    public partial class Funcionario
    {
        [Key]
        [Display(Name = "ID DO FUNCIONÁRIO")]
        public int ID { get; set; }

        [Required(ErrorMessage = "<b style = 'color : black;' > O nome do funcionário é obrigatório.</b>", AllowEmptyStrings = false)]
        [Display(Name = "Nome")]
        public string nome { get; set; }

        [Required(ErrorMessage = "<b style = 'color : black;' > O CPF deve conter 11 caracteres.</b>")]
        [StringLength(11, MinimumLength = 11)]
        [Display(Name = "CPF")]
        public string CPF { get; set; }


        [Required(ErrorMessage = "<b style = 'color : black;' > O email é obrigatório.</b>")]
        [StringLength(100, MinimumLength = 5, ErrorMessage =
          "<b style = 'color : black;' > O email deve ter no mínimo 5 e no máximo 100 caracteres.</b>")]
        [Display(Name = "Email")]
        public string email { get; set; }
    }
}