// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConcessionariaWeb.Model
{
    public partial class Veiculo
    {
        [Key]
        [Display(Name = "ID")]
        public int ID { get; set; }

        
        [Required(ErrorMessage = "<b style = 'color : black;' > A Marca do veículo é obrigatória.</b>", AllowEmptyStrings = false)]
        [Display(Name = "MARCA")]
        public string marca { get; set; }



        [Required(ErrorMessage = "<b style = 'color : black;' > O modelo do veículo é obrigatório.</b>", AllowEmptyStrings = false)]
        [Display(Name = "MODELO")]
        public string modelo { get; set; }



        [StringLength(4, MinimumLength = 4, ErrorMessage =
          "<b style = 'color : black;' > O ano de fabricação necessita de 4 digítos SOMENTE NÚMEROS SÃO ACEITOS.</b>")]
        [Range(1, 99999)]
        [Display(Name = "ANO DE FABRICAÇÃO")]
        public string anoFabricacao { get; set; }


        [Required(ErrorMessage = "<b style = 'color : black;' > O valor do veículo é obrigatório.</b>", AllowEmptyStrings = false)]
        [Display(Name = "VALOR")]
        public string valor { get; set; }
    }
}